function Favourite() {
   return (
      <div style={{ height: '2000px' }}>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
         <div>
            <h1>HEllo</h1>
         </div>
      </div>
   );
}

export default Favourite;
